# azuread_application attributes that are exported

output "audience_object_id" {
  description = "The object id of audience application. Can be used to assign roles to user."
  value       = module.azurerm_app_reg.object_id

}

output "audience_application_id" {
  description = "The audience application id of AzureAD application created."
  value       = module.azurerm_app_reg.client_id
}

output "audience_logo_url" {
  description = "CDN URL to the audience application's logo, as uploaded with the logo_image property."
  value       = module.azurerm_app_reg.logo_url
}

output "audience_disabled_by_microsoft" {
  description = "Whether Microsoft has disabled the registered audience application. If the application is disabled, this will be a string indicating the status/reason, e.g. DisabledDueToViolationOfServicesAgreement."
  value       = module.azurerm_app_reg.disabled_by_microsoft
}

output "audience_publisher_domain" {
  description = "The verified publisher domain for the audience application."
  value       = module.azurerm_app_reg.publisher_domain
}


output "client_object_id" {
  description = "The object id of client application. Can be used to assign roles to user."
  value       = module.azurerm_app_reg_client.object_id

}

output "client_application_id" {
  description = "The client application id of AzureAD application created."
  value       = module.azurerm_app_reg_client.client_id
}

output "client_logo_url" {
  description = "CDN URL to the client application's logo, as uploaded with the logo_image property."
  value       = module.azurerm_app_reg_client.logo_url
}

output "client_disabled_by_microsoft" {
  description = "Whether Microsoft has disabled the registered client application. If the application is disabled, this will be a string indicating the status/reason, e.g. DisabledDueToViolationOfServicesAgreement."
  value       = module.azurerm_app_reg_client.disabled_by_microsoft
}

output "client_publisher_domain" {
  description = "The verified publisher domain for the client application."
  value       = module.azurerm_app_reg_client.publisher_domain
}



# azuread_service_principal attributes that are exported

output "audience_display_name" {
  description = "The display name of the audience application associated with this service principal."
  value       = module.azurerm_service_principal_audienceapp.display_name
}

output "audience_service_principal" {
  description = "The object Id of Service principal for audience app"
  value       = module.azurerm_service_principal_audienceapp.object_id
}

output "audience_app_role_ids" {
  description = "A mapping of app role values to app role IDs, as published by the associated application, intended to be useful when referencing app roles in other resources in your configuration."
  value       = module.azurerm_service_principal_audienceapp.app_role_ids
}

output "audience_oauth2_permission_scope_ids" {
  description = "A mapping of OAuth2.0 permission scope values to scope IDs."
  value       = module.azurerm_service_principal_audienceapp.oauth2_permission_scope_ids
}

output "audience_oauth2_permission_scopes" {
  description = "A mapping of OAuth2.0 permission scope values to scope IDs."
  value       = module.azurerm_service_principal_audienceapp.oauth2_permission_scopes
}

output "audience_app_roles" {
  description = "A mapping of OAuth2.0 permission scope values to scope IDs."
  value       = module.azurerm_service_principal_audienceapp.app_roles
}


output "client_display_name" {
  description = "The display name of the client application associated with this service principal."
  value       = module.azurerm_service_principal_clientapp.display_name
}

output "client_service_principal" {
  description = "The object Id of Service principal of client application."
  value       = module.azurerm_service_principal_clientapp.object_id
}




# azuread_application_password attributes that are exported


output "Client_key_id" {
  description = "A UUID used to uniquely identify this password credential for client app."
  value       = module.azurerm_app_reg_client_pwd.key_id
}

output "client_secret" {
  description = "The password for client application, which is generated by Azure Active Directory."
  value       = module.azurerm_app_reg_client_pwd.value
  sensitive   = true
}


